import time
import threading
from sniper_biz import SteemSniperBackend
import config  # Importa il file di configurazione


SNODES = [
    'https://api.moecki.online',
    'https://api.pennsif.net',
    'https://steemapi.boylikegirl.club',
    'https://cn.steems.top',
    'https://api.worldofxpilar.com',
    'https://api.upvu.org'
]

# Funzione per gestire il voto
def start_voting():
    sniper = SteemSniperBackend()
    sniper.configure(
        posting_key=config.CUR8_POSTING_STEEM,
        voter="cur8",
        interval=1,
        min_voting_power=80,
        max_post_age_minutes=5
    )
    sniper.configure_author("im-ridd", vote_percentage=50, post_delay_minutes=4.9, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("stefano.massari", vote_percentage=5, post_delay_minutes=4, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("mikitaly", vote_percentage=5, post_delay_minutes=4, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("frafiomatale", vote_percentage=5, post_delay_minutes=4, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("rp-k-0", vote_percentage=25, post_delay_minutes=4, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("tangera", vote_percentage=7, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("davilo", vote_percentage=15, post_delay_minutes=3, daily_vote_limit=1, add_comment=False)
 #   sniper.configure_author("messi2", vote_percentage=20, post_delay_minutes=3, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("vingroup", vote_percentage=15, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("karianaporras", vote_percentage=7, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False)
  #  sniper.configure_author("delwal", vote_percentage=7, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False)
  #  sniper.configure_author("haejin", vote_percentage=20, post_delay_minutes=5, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("patjewell", vote_percentage=20, post_delay_minutes=3, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("trafalgar", vote_percentage=30, post_delay_minutes=1.8, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("rme", vote_percentage=5, post_delay_minutes=2.5, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("kabula", vote_percentage=20, post_delay_minutes=3, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("happycapital", vote_percentage=25, post_delay_minutes=4.4, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("zumed", vote_percentage=30, post_delay_minutes=4, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("cjsdns", vote_percentage=10, post_delay_minutes=3, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("mimes", vote_percentage=20, post_delay_minutes=3, daily_vote_limit=1, add_comment=False)
 #   sniper.configure_author("veronicalee", vote_percentage=20, post_delay_minutes=2.5, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("gogikr", vote_percentage=20, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("arbitration", vote_percentage=7, post_delay_minutes=4, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("alvinwales", vote_percentage=7, post_delay_minutes=3, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("indicatormode", vote_percentage=40, post_delay_minutes=4, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("ritzy-writer", vote_percentage=40, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("powergogo", vote_percentage=7, post_delay_minutes=3, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("jgwonkim", vote_percentage=25, post_delay_minutes=3.8, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("sagor1233", vote_percentage=7, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("pmart", vote_percentage=10, post_delay_minutes=3, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("anggali", vote_percentage=10, post_delay_minutes=3, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("fxsajol", vote_percentage=10, post_delay_minutes=3, daily_vote_limit=1, add_comment=False)
  #  sniper.configure_author("alsarzilsiam", vote_percentage=4.5, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("iostkr", vote_percentage=7, post_delay_minutes=3, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("lieutenantdan", vote_percentage=30, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("ini4909", vote_percentage=15, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("inchonbitcoin", vote_percentage=15, post_delay_minutes=4, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("nazmulhudaa", vote_percentage=15, post_delay_minutes=3, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("pomeline", vote_percentage=7.5, post_delay_minutes=3, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("saikat890", vote_percentage=5, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("amarbanglablog", vote_percentage=4.5, post_delay_minutes=3.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
 #   sniper.configure_author("cryptopie", vote_percentage=5, post_delay_minutes=4, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("optv1", vote_percentage=15, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
  #  sniper.configure_author("shuvo35", vote_percentage=15, post_delay_minutes=4.7, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("justyy", vote_percentage=10, post_delay_minutes=4, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("arsalaan", vote_percentage=25, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("colds", vote_percentage=45, post_delay_minutes=3, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("steem-articles", vote_percentage=20, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("countach.rico", vote_percentage=45, post_delay_minutes=3, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("abbc-reports", vote_percentage=20, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("successgr", vote_percentage=7, post_delay_minutes=1.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("bbn1", vote_percentage=5, post_delay_minutes=2.9, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
   # sniper.configure_author("jsj1215", vote_percentage=5, post_delay_minutes=3, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    #sniper.configure_author("swagata21", vote_percentage=5, post_delay_minutes=3.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("thinking.element", vote_percentage=30, post_delay_minutes=4.3, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
#    sniper.configure_author("dexsyluz", vote_percentage=5, post_delay_minutes=4, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("abb-featured", vote_percentage=30, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("t-s-k", vote_percentage=40, post_delay_minutes=4, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
   # sniper.configure_author("blockstudent", vote_percentage=5, post_delay_minutes=2.9, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("boc-reports", vote_percentage=15, post_delay_minutes=4.3, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("bumblecat", vote_percentage=20, post_delay_minutes=4, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
#    sniper.configure_author("h4lab", vote_percentage=5, post_delay_minutes=3.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("jihad75", vote_percentage=20, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("leguna", vote_percentage=20, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("lyh5926", vote_percentage=25, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
   # sniper.configure_author("mohammadfaisal", vote_percentage=5, post_delay_minutes=4, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("nilaymajumder", vote_percentage=5, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
 #   sniper.configure_author("nusuranur", vote_percentage=15, post_delay_minutes=3, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
 #   sniper.configure_author("rex-sumon", vote_percentage=5, post_delay_minutes=4.7, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("sa-reports", vote_percentage=20, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("un-stoppable", vote_percentage=35, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
#    sniper.configure_author("winkles", vote_percentage=20, post_delay_minutes=4, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
#    sniper.configure_author("zzan7", vote_percentage=5, post_delay_minutes=4, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("uco.bnb-d", vote_percentage=10, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("uco.btc-l", vote_percentage=15, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("hotspotitaly", vote_percentage=10, post_delay_minutes=4.8, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
#    sniper.configure_author("davidesimoncini", vote_percentage=7, post_delay_minutes=3.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("mia.fobos", vote_percentage=5, post_delay_minutes=4.3, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("luciojolly", vote_percentage=30, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("tasubot", vote_percentage=7.5, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("fahriz4l", vote_percentage=25, post_delay_minutes=3, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
#    sniper.configure_author("grefn", vote_percentage=20, post_delay_minutes=4.7, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
  #  sniper.configure_author("info-steem", vote_percentage=15, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("wildnature1", vote_percentage=5, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("dexpartacus", vote_percentage=15, post_delay_minutes=4.8, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("centering", vote_percentage=3, post_delay_minutes=3, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("rtytf2", vote_percentage=5, post_delay_minutes=2.6, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("boddhisattva", vote_percentage=10, post_delay_minutes=3.8, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("steemhop.org", vote_percentage=10, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("raintears", vote_percentage=40, post_delay_minutes=3.8, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("steemzzang", vote_percentage=25, post_delay_minutes=3, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("diamond31", vote_percentage=15, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("upvu.witness", vote_percentage=30, post_delay_minutes=4, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("khaiyoui", vote_percentage=10, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("dodoim", vote_percentage=10, post_delay_minutes=3, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("hodolbak", vote_percentage=10, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("ety001", vote_percentage=20, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("jjy", vote_percentage=15, post_delay_minutes=3, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("fj1", vote_percentage=5, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("pennsif", vote_percentage=15, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("bigram13", vote_percentage=10, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("jrcornel", vote_percentage=15, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("thedogekid", vote_percentage=10, post_delay_minutes=2.8, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("rp-k-0", vote_percentage=15, post_delay_minutes=4, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("threadstream", vote_percentage=15, post_delay_minutes=4, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("feuerelfe", vote_percentage=15, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("puss.coin", vote_percentage=20, post_delay_minutes=3, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("tfc-reports", vote_percentage=15, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("ocean-trench", vote_percentage=25, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("georgia14", vote_percentage=5, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("abb-fun", vote_percentage=30, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("blackeyedm", vote_percentage=20, post_delay_minutes=3.9, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("blacks", vote_percentage=30, post_delay_minutes=4, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("whoisjohn", vote_percentage=15, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("curious.mind", vote_percentage=30, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("darklights", vote_percentage=35, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("heartwarming", vote_percentage=15, post_delay_minutes=4.4, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("ciusk", vote_percentage=5, post_delay_minutes=4.7, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("jejudomin", vote_percentage=15, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("winkles", vote_percentage=15, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("girolamomarotta", vote_percentage=10, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("mad-runner", vote_percentage=10, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("successgr", vote_percentage=15, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("parkname", vote_percentage=15, post_delay_minutes=3, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("luna88", vote_percentage=10, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("libera-tor", vote_percentage=5, post_delay_minutes=3, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("lee1004", vote_percentage=10, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("xiguang", vote_percentage=5, post_delay_minutes=4.9, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("oswaldocuarta", vote_percentage=5, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False, add_image=False, comment_text="Bel post!")
    sniper.configure_author("ppomppu", vote_percentage=20, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("realrobinhood", vote_percentage=10, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("krishiv-g", vote_percentage=5, post_delay_minutes=4.9, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("cancerdoctor", vote_percentage=5, post_delay_minutes=3, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("yela", vote_percentage=15, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("abuse-watcher", vote_percentage=15, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("alimkhan", vote_percentage=5, post_delay_minutes=4.8, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("arman-alif", vote_percentage=15, post_delay_minutes=4, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("anailuj1992", vote_percentage=25, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("dove11", vote_percentage=5, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("sualeha", vote_percentage=5, post_delay_minutes=3.2, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("zzan7", vote_percentage=15, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("blaze.apps", vote_percentage=30, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("cur8.witness", vote_percentage=30, post_delay_minutes=4.9, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("solaymann", vote_percentage=2, post_delay_minutes=4.9, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("samhunnahar", vote_percentage=2, post_delay_minutes=4.9, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("max-pro", vote_percentage=5, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("afzalqamar", vote_percentage=5, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("ahsansharif", vote_percentage=5, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("narocky71", vote_percentage=5, post_delay_minutes=4.5, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("issambashir", vote_percentage=25, post_delay_minutes=3.8, daily_vote_limit=2, add_comment=False)
    sniper.configure_author("new.chain-stats", vote_percentage=35, post_delay_minutes=3.9, daily_vote_limit=1, add_comment=False)
    sniper.configure_author("rokonn", vote_percentage=10, post_delay_minutes=4.8, daily_vote_limit=1, add_comment=False)



    sniper.start()



if __name__ == "__main__":
    print("Starting combined task")

    # Avvio del processo di voting in un thread separato
    voting_thread = threading.Thread(target=start_voting)
    voting_thread.daemon = True  # Questo thread chiuderà quando il programma principale terminerà
    voting_thread.start()

    # Ciclo principale per postare i draft
    while True:
        print("Curation ongoing...")
        time.sleep(6000)  # Attende 60 secondi prima di eseguire di nuovo
